Charter extension 2024-03
w3c/rdf-star-wg-charter pull request #57
Opened 2024-03-04 20:43 UTC by pchampin

2024-03-04 21:43 UTC, rdfguy approved these changes
OK as far as I can tell.

2024-03-26 20:41 UTC, TallTed requested changes

2024-03-26 20:41 UTC, TallTed commented on index.html
> +        <p>The scope of this Working Group is to update the recommendations defining RDF 1.1 and SPARQL 1.1, extending them with the features introduced by RDF-star. More precisely, RDF-star introduc
```suggestion
        <p>The scope of this Working Group is to update the recommendations defining RDF 1.1 and SPARQL 1.1, extending them with the features introduced by RDF-star. More precisely, RDF-star introduces the notion of <em>quoted triple</em> to express statements about statements. The abstract and concrete syntaxes of RDF and SPARQL, as well as their respective semantics, are to be extended to support this new feature.
```

2024-03-26 20:41 UTC, TallTed commented on index.html
> +                  Rechartered for two more years, to 1) complete the work on RDF 1.2 and SPARQL 1.2 deliverables, and 2) switch to maintenance mode afterwards.
```suggestion
                  Rechartered for two more years, to 1) complete the work on RDF 1.2 and SPARQL 1.2 deliverables, and 2) switch to maintenance mode thereafter.
```

2024-03-27 17:46 UTC, gkellogg commented
The SPARQL 1.2 Community Group is now the SPARQL Dev Community Group.

Even though the RDF Dataset Canonicalization WG charter expires this summer, they should probably be listed for coordination.

2024-03-28 07:25 UTC, pchampin commented
> Is this an opportunity to change the name of the WG to "RDF 1.2 Working Group"?

To be clear: in retrospect, I prefer "RDF 1.2", I wish we had chose that name of the WG instead of "RDF-star".
I don't know if it is OK to rename a WG in a rechartering, I'm guessing it would be).

However, I'm afraid that some people might perceive a renaming as an attempt to change the scope of the WG, and that it would create unnecessary friction.

When we have our RECs published (RDF 1.2 xyz and SPARQL 1.2 xyz) and we go to a maintenance group on these specs, I think it will be less controversial to rename to "RDF 1.2 WG". But before that, I'm reluctant.

2024-03-28 10:56 UTC, afs commented
> some people might perceive

It's tricky. At the move to a maintenance group, a change of name may cause increased expectations.

How about adding to the description to explain the change of name because of the existing remit over all the docs?

2024-04-04 16:43 UTC, gkellogg commented
I wonder if the issue with TAG discussions on Polyglot formats bears any relation on RDF/XML or SPARQL Result formats. It would also impact RDFa and CSVW, which we're not working on, but are related. See https://github.com/ietf-wg-mediaman/suffixes/issues and https://mailarchive.ietf.org/arch/msg/media-types/iWc8TLcWOyO0jyqeiuF9VCZClIs/.

2024-05-30 16:43 UTC, afs commented on index.html
> +              <p class="milestone"><b>Expected completion:</b> Q1 2025</p>
Here and sparql-results-json, it's Q1 2025, but other SPARQl specs are Q2 and the timeline says "Q2 2025: Recommendation of SPARQL 1.2 deliverables".

```suggestion
              <p class="milestone"><b>Expected completion:</b> Q2 2025</p>
```

2024-05-30 16:43 UTC, afs commented on index.html
> +              <p class="milestone"><b>Expected completion:</b> Q1 2025</p>
```suggestion
              <p class="milestone"><b>Expected completion:</b> Q2 2025</p>
```

2024-06-04 20:14 UTC, TallTed approved these changes

2024-06-13 11:19 UTC, merged